/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mealymodel.xtext;

import org.eclipse.emf.mwe2.language.Mwe2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MealymachineDslStandaloneSetup extends Mwe2StandaloneSetupGenerated {

	public static void doSetup() {
		new MealymachineDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
