/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mealymodel.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MealymachineDslStandaloneSetup extends MealymachineDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MealymachineDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
