/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.ltl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LtlUiModule extends AbstractLtlUiModule {

	public LtlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
