/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mealymodel.xtext.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.mealymodel.xtext.parser.antlr.internal.InternalMealymachineDslParser;
import hu.bme.mit.mealymodel.xtext.services.MealymachineDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MealymachineDslParser extends AbstractAntlrParser {

	@Inject
	private MealymachineDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMealymachineDslParser createParser(XtextTokenStream stream) {
		return new InternalMealymachineDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MealyMachine";
	}

	public MealymachineDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MealymachineDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
