/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mealymodel.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MealymachineDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("hu/bme/mit/mealymodel/xtext/parser/antlr/internal/InternalMealymachineDsl.tokens");
	}
}
