/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mealymodel.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMealymachineDslScopeProvider extends DelegatingScopeProvider {
}
