/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mealymodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMealyDslScopeProvider extends DelegatingScopeProvider {
}
