/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.ltl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.ltl.LtlRuntimeModule;
import hu.bme.mit.ltl.LtlStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LtlIdeSetup extends LtlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LtlRuntimeModule(), new LtlIdeModule()));
	}
	
}
