/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mealymodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MealyDslStandaloneSetup extends MealyDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MealyDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
