/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.ltl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLtlScopeProvider extends DelegatingScopeProvider {
}
