/*
 * generated by Xtext 2.23.0
 */
package hu.bme.mit.ltl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LtlStandaloneSetup extends LtlStandaloneSetupGenerated {

	public static void doSetup() {
		new LtlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
